# Generated by Django 3.1.4 on 2021-01-21 23:54

import apps.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20201122_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrojanConfig',
            fields=[
                ('proxy_node', models.OneToOneField(help_text='代理节点', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trojan_config', serialize=False, to='proxy.proxynode', verbose_name='代理节点')),
                ('config', models.JSONField(default=apps.utils.get_default_trojan_config, verbose_name='配置')),
            ],
            options={
                'verbose_name': 'Trojan配置',
                'verbose_name_plural': 'Trojan配置',
            },
        ),
    ]
