# Generated by Django 5.0 on 2025-12-13 16:45

import apps.proxy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0029_proxynode_native_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='HysteriaConfig',
            fields=[
                ('proxy_node', models.OneToOneField(help_text='代理节点', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hysteria_config', serialize=False, to='proxy.proxynode', verbose_name='代理节点')),
                ('port_hop_min', models.IntegerField(default=0, verbose_name='端口跳跃最小值')),
                ('port_hop_max', models.IntegerField(default=0, verbose_name='端口跳跃最大值')),
                ('port_hop_interval', models.IntegerField(default=0, verbose_name='端口跳跃间隔(秒)')),
                ('multi_user_port', models.IntegerField(blank=True, help_text='单端口多用户端口', null=True, verbose_name='多用户端口')),
            ],
            options={
                'verbose_name': 'Hysteria配置',
                'verbose_name_plural': 'Hysteria配置',
            },
            bases=(models.Model, apps.proxy.models.resetPortMixin),
        ),
        migrations.RenameIndex(
            model_name='usertrafficlog',
            new_name='proxy_usert_user_id_9c6495_idx',
            old_fields=('user', 'proxy_node', 'created_at'),
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='ehco_listen_type',
            field=models.CharField(choices=[('raw', 'raw'), ('ws', 'ws'), ('wss', 'wss')], default='raw', max_length=64, verbose_name='隧道监听类型'),
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='ehco_transport_type',
            field=models.CharField(choices=[('raw', 'raw'), ('ws', 'ws'), ('wss', 'wss')], default='raw', max_length=64, verbose_name='隧道传输类型'),
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='node_type',
            field=models.CharField(choices=[('ss', 'ss'), ('hysteria', 'hysteria'), ('trojan', 'trojan'), ('ssr', 'ssr'), ('vmess', 'vmess'), ('vless', 'vless')], default='ss', max_length=32, verbose_name='节点类型'),
        ),
        migrations.AlterField(
            model_name='relayrule',
            name='listen_type',
            field=models.CharField(choices=[('raw', 'raw'), ('ws', 'ws'), ('wss', 'wss')], default='raw', max_length=64, verbose_name='监听类型'),
        ),
        migrations.AlterField(
            model_name='relayrule',
            name='transport_type',
            field=models.CharField(choices=[('raw', 'raw'), ('ws', 'ws'), ('wss', 'wss')], default='raw', max_length=64, verbose_name='传输类型'),
        ),
    ]
