# Generated by Django 5.0 on 2025-12-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0030_hysteriaconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hysteriaconfig',
            name='port_hop_interval',
            field=models.IntegerField(default=60, verbose_name='端口跳跃间隔(秒)'),
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='node_type',
            field=models.CharField(choices=[('ss', 'ss'), ('hysteria2', 'hysteria2'), ('trojan', 'trojan'), ('ssr', 'ssr'), ('vmess', 'vmess'), ('vless', 'vless')], default='ss', max_length=32, verbose_name='节点类型'),
        ),
    ]
