# Generated by Django 5.0 on 2026-04-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0031_alter_hysteriaconfig_port_hop_interval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hysteriaconfig",
            name="obfs_pass",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="混淆方式"
            ),
        ),
        migrations.AlterField(
            model_name="proxynode",
            name="xray_grpc_port",
            field=models.IntegerField(default=8121, verbose_name="xray grpc port"),
        ),
    ]
