# Generated by Django 5.0 on 2026-05-15 09:34

import apps.proxy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0032_hysteriaconfig_obfs_pass_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnyTlsConfig",
            fields=[
                (
                    "proxy_node",
                    models.OneToOneField(
                        help_text="代理节点",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="anytls_config",
                        serialize=False,
                        to="proxy.proxynode",
                        verbose_name="代理节点",
                    ),
                ),
                (
                    "multi_user_port",
                    models.IntegerField(
                        blank=True,
                        help_text="单端口多用户端口",
                        null=True,
                        verbose_name="多用户端口",
                    ),
                ),
                (
                    "padding_scheme",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        verbose_name="padding 方案",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anytls配置",
                "verbose_name_plural": "Anytls配置",
            },
            bases=(models.Model, apps.proxy.models.resetPortMixin),
        ),
        migrations.AlterField(
            model_name="proxynode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("ss", "ss"),
                    ("hysteria2", "hysteria2"),
                    ("trojan", "trojan"),
                    ("ssr", "ssr"),
                    ("vmess", "vmess"),
                    ("vless", "vless"),
                    ("anytls", "anytls"),
                ],
                default="ss",
                max_length=32,
                verbose_name="节点类型",
            ),
        ),
    ]
