# Generated by Django 5.0 on 2026-06-10 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0033_anytlsconfig_alter_proxynode_node_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="anytlsconfig",
            name="padding_mode",
            field=models.CharField(
                choices=[("off", "关闭"), ("manual", "手动填写"), ("auto", "自动轮换")],
                default="off",
                max_length=16,
                verbose_name="padding模式",
            ),
        ),
        migrations.AddField(
            model_name="anytlsconfig",
            name="padding_rotation_interval",
            field=models.PositiveIntegerField(
                default=1,
                help_text="自动轮换模式下每隔多少小时生成新的padding方案，需 ≥ 节点配置重载间隔",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(168),
                ],
                verbose_name="轮换间隔(小时)",
            ),
        ),
        migrations.AlterField(
            model_name="anytlsconfig",
            name="padding_scheme",
            field=models.CharField(
                blank=True, max_length=2048, null=True, verbose_name="padding 方案"
            ),
        ),
    ]
