# Generated by Django 5.0 on 2026-06-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0034_anytlsconfig_padding_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anytlsconfig",
            name="cert_mode",
            field=models.CharField(
                choices=[("acme", "ACME 自动签发"), ("self_signed", "自签名证书")],
                default="acme",
                max_length=16,
                verbose_name="证书模式",
            ),
        ),
        migrations.AddField(
            model_name="hysteriaconfig",
            name="cert_mode",
            field=models.CharField(
                choices=[("acme", "ACME 自动签发"), ("self_signed", "自签名证书")],
                default="acme",
                max_length=16,
                verbose_name="证书模式",
            ),
        ),
        migrations.AddField(
            model_name="trojanconfig",
            name="cert_mode",
            field=models.CharField(
                choices=[("acme", "ACME 自动签发"), ("self_signed", "自签名证书")],
                default="acme",
                max_length=16,
                verbose_name="证书模式",
            ),
        ),
    ]
