# Generated by Django 5.0 on 2026-06-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0035_add_cert_mode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proxynode",
            old_name="ehco_log_level",
            new_name="log_level",
        ),
        migrations.RemoveField(
            model_name="proxynode",
            name="ehco_reload_interval",
        ),
        migrations.AddField(
            model_name="proxynode",
            name="reload_interval",
            field=models.IntegerField(default=30, verbose_name="配置重载间隔"),
        ),
    ]
