name: build-runtime-image
on:
  push:
    branches:
      - build
      - master
      - dev
      - test/gkirito/ci/support-multi-platforms
    paths:
      - "pyproject.toml"
      - "deploy/Dockerfile.RUNTIME"
  workflow_dispatch:
jobs:
  build-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: set up qemu
        uses: docker/setup-qemu-action@v2

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build & push runtime image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: gkirito/django-sspanel:runtime
          file: deploy/Dockerfile.RUNTIME
          platforms: linux/amd64,linux/arm64

      - name: build & push nginx image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: gkirito/django-sspanel:nginx
          file: deploy/Dockerfile.NGINX
          platforms: linux/amd64,linux/arm64
